import type { NextPage } from 'next';
import Head from 'next/head';
import { Board } from '@prisma/client';
import Link from 'next/link';
import { useQuery } from 'react-query';
import { CreateBoard } from 'components/app/CreateBoard';
import { useSession } from 'next-auth/react';

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  const { isLoading, error, data } = useQuery('boards', () =>
    fetch('/api/boards').then((res) => res.json())
  );

  if (isLoading) return <p>Loading...</p>;

  if (error) return <p> An error has occurred: {error.message}</p>;
  return (
    <div>
      <Head>
        <title>WorkOS Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {status === 'unauthenticated' ? (
        <h1 className="text-3xl flex items-center justify-center mt-28">
          {' '}
          Log in to start using the app!
        </h1>
      ) : (
        <div className="max-w-screen-2xl mx-auto px-28 py-16">
          {data.boards.length === 0 ? (
            <h1 className="text-lg mb-5">
              You don't have any boards, start by creating a new one
            </h1>
          ) : (
            <ul className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 mb-5 gap-10">
              {data.boards.map((board: Board) => (
                <Link key={board.id} href={`/board/${board.id}`}>
                  <a className="hover:text-blue-500 hover:scale-105 transform transition-transform shadow p-5 rounded-lg">
                    <p className="font-medium text-xl mb-3">{board.title}</p>
                    <p className="text-lg">{board.description}</p>
                  </a>
                </Link>
              ))}
            </ul>
          )}
          <CreateBoard />
        </div>
      )}
    </div>
  );
};

export default Home;
